config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'
  get 'signup',to: 'users#new'
  resources :users, except: [:new]
  resources :articles

  get 'login',to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user

    validates :title, presence: true, length: {minimum: 3, maximum: 50}

    validates :description, presence: true, length: {minimum: 10, maximum: 300}

    validates :user_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord

    validates :name, presence: true, length: { minimum: 3, maximum: 25 }

    validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy

    before_save {self.email = email.downcase}

    validates :username, presence: true,
    uniqueness: { case_sensitive: false },
    length: { minimum: 3, maximum: 25 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 },
    uniqueness: { case_sensitive: false },
    format: { with: VALID_EMAIL_REGEX }

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in to perform that action"
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end


    def create
        #debugger
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:notice] = "Successfully created"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def show

    end

    def destroy

        @article.destroy
        flash[:notice] = "Successfully deleted"
        redirect_to articles_path
    end

    def edit

    end

    def update

        if @article.update(article_params)
            flash[:notice]="Successfully updated"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description)
    end

    def require_same_user
        if current_user != @article.user and !current_user.admin?
            flash[:danger] = "You can only edit or delete your own articles"
            redirect_to root_path
        end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end


    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in"
            redirect_to user_path(user)
        else
          flash.now[:danger] = "There was something wrong with your login information"
        render 'new'
        end
    end


    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the alpha blog #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
        flash[:notice]="Successfully updated"
        redirect_to articles_path(@user)
    else
        render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
      @users = User.all
  end

  def destroy
      @user = User.find(params[:id])
      @user.destroy
      flash[:danger] = "User and all articles created by user have been deleted"
      redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end


  def require_same_user
    if current_user != @user
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<table>

    <tr>
        <th>ID</th>
        <th>This is title</th>

        <th>Description</th>
        <th>Written by</th>
        <th>Writer's Email</th>
        <th>Created at</th>
        <th>Updated at</th>

    </tr>

    <% obj.each do |article| %>
    <% n = "N/A" %>
    <tr>
        <td><%= article.id %></td>
        <td><%= article.title %></td>

        <td><%= article.description %></td>

        <td><%= article.user.username if article.user %><span><%= n if !article.user %> </span></td>

        <td><%= article.user.email if article.user %><span><%= n if !article.user %> </span></td>

        <td><%= time_ago_in_words(article.created_at) %></td>

        <td><%= time_ago_in_words(article.updated_at) %></td>

        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
            <td><%= link_to 'Show', article_path(article) %></td>
            <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
        <% end %>
    </tr>

    <% end %>

</table>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>

<h2>The following errors prevented the article from getting created</h2>

<ul>

<% @article.errors.full_messages.each do |msg| %>

    <li><%= msg %></li>

<% end %>

</ul>

<% end %>

<%= form_for @article do |f| %>

<p>

<%= f.label :title %><br/>

<%= f.text_field :title %>

</p>

<p>

<%= f.label :description %><br/>

<%= f.text_area :description %>

</p>

<p>

<%= f.submit %>

</p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>

<p>

<button> <%= link_to "Create new article", new_article_path %></button>

<button> <%= link_to "SignUp", new_user_path %> </button>

</p>

<%= render 'article', obj: @articles %>

app/views/articles/new.html.erb
<h1>Create Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>
<%= link_to "Add new article", new_article_path%>
<p>
    Title: <%= @article.title %>
</p>
        <tr>
        <p>written by: <%= link_to @article.user.username, user_path(@article.user) %></p>
        </tr>
<p>
    Description: <%= @article.description %>
</p>

<%= link_to "Edit this article", edit_article_path(@article) %> |
<button><%= link_to "Back to articles listing", articles_path %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |name, msg| %>

    <ul>
    <li><%= msg %></li>
    </ul>

  <% end %>

  <% if logged_in? %>
    <%= link_to 'Log Out', logout_path, method: :delete %>
  <% else %>
    <button> <%= link_to "LogIn", login_path %> </button>
  <% end %>

    <%= yield %>
    <h1>End</h1>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>

    <h2>The following errors prevented the article from getting created</h2>

    <ul>

    <% @user.errors.full_messages.each do |msg| %>

        <li><%= msg %></li>

    <% end %>

    </ul>

<% end %>

<%= form_for @user do |f| %>

<p>

<%= f.label :username %><br/>

<%= f.text_field :username %>

</p>

<p>

<%= f.label :email %><br/>

<%= f.email_field :email %>

</p>

<p>

<%= f.label :password %><br/>

<%= f.password_field :password %>

</p>

<p>

<%= f.submit(@user.new_record? ? "Sign up" : "Update account") %>

</p>

<% end %>

app/views/users/edit.html.erb
<h1>Edit Your account</h1>
<%= render 'form'%>

app/views/users/index.html.erb
<h1>List of all Users</h1>

<table>

    <tr>
        <th>ID</th>

        <th>User Name</th>
        <th>User Email</th>
        <th>Articles Count</th>

    </tr>

        <%= @users.each do |user| %>
        <tr>
            <td><%= user.id %></td>
            <td><%= link_to user.username, user_path(user) %></td>

            <td><%= user.email %></td>
            <td><%= user.articles.count%></td>
            <% if logged_in? and current_user.admin? %>
                <td><%= link_to "Delete this user", user_path(user), method: :delete,
                data: { confirm: "Are you sure you want to delete the user and all their articles?" } %></td>
            <% end %>
            <br/>
        </tr>
        <%end%>


</table>

app/views/users/new.html.erb
<h1>Create Your account</h1>
<%= render 'form'%>

app/views/users/show.html.erb
<h1>User Info</h1>

<h2><%= @user.username %>'s articles</h2>

<%= render 'articles/article', obj: @user.articles %>